name: Fraud Email Alerts

on:
  schedule:
    - cron: "30 3 * * *"   # Daily 9:00 AM Sri Lanka time
  workflow_dispatch:

jobs:
  send-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pandas gdown

      - name: Send fraud alert email
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        run: python send_high_risk_email.py
